name:                impvol
version:             0.1.0.0
github:              "feio-ai/impvol"
license:             BSD3
author:              "Allen VanNoppen"
maintainer:          "feioaccel@gmail.com"
copyright:           "2020 Allen VanNoppen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Simple Haskell Wrapper for Peter Jaeckel's Implied Volatility
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/feio-ai/impvol#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules: Function.Export.LBR
  extra-libraries: lets_be_rational

tests:
  impvol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - impvol
